### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by JohnPlanetary** [TheChiefMeat/minisign-gui#1]
"Failed to execute script minisign-gui"

It is in the same directory of the minisign.exe, on Windows 10 Home x64 1909 version.

With or without elevation privileges it won't work.
1.0, or 1.1 versions of Minisign-gui don't work.

**Comment by TheChiefMeat** [comment]
Hi there, thank you for the bug report. Can you try out the pre-release version below and see if that works for you:

https://github.com/TheChiefMeat/minisign-gui/releases/download/1.2/minisign-gui.zip

**Comment by JohnPlanetary** [comment]
Thanks for the fast answer.
I confirm, now it is working properly on my machine.
I tested all the functions and they seem to work properly.
Thanks!

**Comment by TheChiefMeat** [comment]
No worries, enjoy :)
